# Site settings
title: Happy Coding
email: wanggenguo@yahoo.com
description: "Keep thinking"
baseurl: ""
url: "http://genguowang.github.io"
#twitter_username: jekyllrb
github_username:  GenguoWang

# Build settings
markdown: kramdown
permalink: pretty
timezone: GMT
